#include "control.h"
#include "../smf/smf.h"
#include "../img/img.h"
#include "../glsl/glsl.h"

Control::Control() {
    std::ifstream file("resources/config.json");
    json data;
    file >> data;
    std::string Fname = data["FilePath"];
    strncpy(i_FileName, Fname.c_str(), sizeof(i_FileName) - 1);
    i_FileName[sizeof(i_FileName) - 1] = '\0';
    i_glslVer = data["glslVer"];
	i_glslMode = data["glslMode"];
}

Control::~Control() {
    json data;

    data["FilePath"] = (std::string)i_FileName;
    data["glslVer"] = (std::string)i_glslVer;
    data["glslMode"] = (std::string)i_glslMode;

    std::ofstream file("resources/config.json");
    if (file.is_open()) {
        file << data.dump(2);
    }
}


void Control::Start() {

}

void Control::Update(float Delta) {
	ImGui::Begin("SAM");

    if (ImGui::Button("Compile")) Compile();
	ImGui::SameLine();
    if (ImGui::Button("Save")) {
        GetParent()->FindComponent<Smf>()->Save();
        GetParent()->FindComponent<Img>()->Save();
        GetParent()->FindComponent<Glsl>()->Save();
    }

	ImGui::InputText("File Name", i_FileName, 256);


	ImGui::End();
}

void Control::Compile() {

    GetParent()->FindComponent<Smf>()->Save();
    GetParent()->FindComponent<Img>()->Save();
    GetParent()->FindComponent<Glsl>()->Save();

    std::string h = R"(#pragma once
#include <Smq.h>

// This code is generated by SAM.

void initSam();
void quitSam();

)";
    std::string cpp = R"(
#include "sam.h"
#include <Include.h>

// This code is generated by SAM.

void Ismf();
void Qsmf();

void Iimg();
void Qimg();

void Iglsl();
void Qglsl();

void initSam() {
    Ismf();
    Iimg();
    Iglsl();
}

void quitSam() {
    Qsmf();
    Qimg();
    Qglsl();
}

)";

    cpp += GetParent()->FindComponent<Smf>()->smf_toCpp();
    h += GetParent()->FindComponent<Smf>()->smf_toH();

    cpp += GetParent()->FindComponent<Img>()->img_toCpp();
    h += GetParent()->FindComponent<Img>()->img_toH();

    cpp += GetParent()->FindComponent<Glsl>()->glsl_toCpp();
    h += GetParent()->FindComponent<Glsl>()->glsl_toH();

	smq::SaveFile((std::string)i_FileName + "sam.cpp", cpp);
    smq::SaveFile((std::string)i_FileName + "sam.h", h);
}