
#include "sam.h"
#include <Include.h>

// This code is generated by SAM.

void Ismf();
void Qsmf();

void Iimg();
void Qimg();

void Iglsl();
void Qglsl();

void initSam() {
    Ismf();
    Iimg();
    Iglsl();
}

void quitSam() {
    Qsmf();
    Qimg();
    Qglsl();
}

smq::Mesh* smf[1];
smq::Mesh* GetMesh(Meshes mesh) {
    return smf[static_cast<unsigned int>(mesh)];
}

void Ismf() {

}

void Qsmf() {
    for (int i = 0; i < 0; i++) {
        delete smf[i];
    }
}

smq::Texture* img[1];
smq::Texture* GetTexture(Textures texture) {
    return img[static_cast<unsigned int>(texture)];
}

void Iimg() {
img[0] = new smq::Texture("resources/textures/blocks.png");

}

void Qimg() {
    for (int i = 0; i < 1; i++) {
        delete img[i];
    }
}


smq::Material* mat[2];


void CompileShaderProgram(unsigned int& program, const char* Code, unsigned int type) {
    program = glCreateShader(type);
    glShaderSource(program, 1, &Code, nullptr);
    glCompileShader(program);

    int ok;
    glGetShaderiv(program, GL_COMPILE_STATUS, &ok);
    if (!ok) {
        char log[1024];
        glGetShaderInfoLog(program, 1024, nullptr, log);
        smq::Error(log);
    }
}


unsigned int Shader(unsigned int vs,unsigned int fs) {
    unsigned int i_shader = glCreateProgram();

    glAttachShader(i_shader, vs);
    glAttachShader(i_shader, fs);
    glLinkProgram(i_shader);
    return i_shader;
}

smq::Material* GetMaterial(Materials material) {
	return mat[static_cast<unsigned int>(material)];
}

void Iglsl() {

unsigned int Shaders_shadow_vs_glsl;
CompileShaderProgram(Shaders_shadow_vs_glsl,R"(
#version 460 core


layout(location = 0) in vec4 position;
layout(location = 1) in vec2 texCoord;
layout(location = 2) in vec3 normals;

out vec2 o_texCoord;
out vec3 o_normals;
out vec3 o_pos;

uniform mat4 u_mvp;
uniform mat3 u_normal_mvp;
uniform mat4 u_model;

void main() {
    
    gl_Position = u_mvp * position;
    o_texCoord = texCoord;
    o_normals = u_normal_mvp * normals;
    o_pos = vec3(u_model * vec4(position.xyz, 1.0));
})", GL_VERTEX_SHADER); 

unsigned int Shaders_shadow_fs_glsl;
CompileShaderProgram(Shaders_shadow_fs_glsl,R"(
#version 460 core


layout(location = 0) out vec4 color;

in vec2 o_texCoord;
in vec3 o_normals;
in vec3 o_pos;

uniform sampler2D u_tex;

struct PointLight {
    vec4 position;
    vec4 color;
};

layout(std430, binding = 0) readonly buffer LightBuffer {
    PointLight lights[];
};

uniform int u_lightCount;

vec3 CalculatePointLight(PointLight light, vec3 normal, vec3 fragPos) {
    vec3 lightPos   = light.position.xyz;
    float radius    = light.position.w;
    vec3 lightColor = light.color.rgb;
    float intensity = light.color.w;

    vec3 lightVec = lightPos - fragPos;
    float dist = length(lightVec);

    if(dist > radius) {
        return vec3(0.0);
    }

    vec3 lightDir = normalize(lightVec);

    float diff = max(dot(normal, lightDir), 0.0);

    float attenuation = clamp(1.0 - dist / radius, 0.0, 1.0);

    return lightColor * intensity * diff * attenuation;
}

void main() {
    vec4 texColor = texture(u_tex, o_texCoord);
    vec3 norm = normalize(o_normals);
    
    vec3 lighting = vec3(0.0);

    for(int i = 0; i < u_lightCount; i++) {
        lighting += CalculatePointLight(lights[i], norm, o_pos);
    }

    vec3 ambient = vec3(0.05) * texColor.rgb;
    
    vec3 finalColor = ambient + (lighting * texColor.rgb);
    color = vec4(finalColor, 1.0);
})", GL_FRAGMENT_SHADER); 

unsigned int Shaders_no_mvp_vs_glsl;
CompileShaderProgram(Shaders_no_mvp_vs_glsl,R"(
#version 460 core


layout(location = 0) in vec4 position;
layout(location = 1) in vec2 texCoord;

out vec2 o_texCoord;

void main() {
    
    gl_Position = position;
    o_texCoord = texCoord;

})", GL_VERTEX_SHADER); 

unsigned int Shaders_pass_fs_glsl;
CompileShaderProgram(Shaders_pass_fs_glsl,R"(
#version 460 core


layout(location = 0) out vec4 color;
in vec2 o_texCoord;

uniform sampler2D u_tex;
uniform sampler2D u_depth;

void main() {
    color = texture(u_tex, o_texCoord);
})", GL_FRAGMENT_SHADER); 

unsigned int shaders0 = Shader(Shaders_shadow_vs_glsl, Shaders_shadow_fs_glsl);


unsigned int shaders1 = Shader(Shaders_no_mvp_vs_glsl, Shaders_pass_fs_glsl);


glDeleteShader(Shaders_shadow_vs_glsl);

glDeleteShader(Shaders_shadow_fs_glsl);

glDeleteShader(Shaders_no_mvp_vs_glsl);

glDeleteShader(Shaders_pass_fs_glsl);



std::vector<unsigned int> uniforms_s_shadow;
uniforms_s_shadow.resize(5);
std::vector<smq::GlAtribute> atributes_s_shadow;
atributes_s_shadow.resize(5);
uniforms_s_shadow[0] = glGetUniformLocation(shaders0, "u_mvp");
atributes_s_shadow[0].type = smq::GlUniform_Mat4;
atributes_s_shadow[0].m4 = {0.0f,0.0f,0.0f,0.0f, 0.0f,0.0f,0.0f,0.0f, 0.0f,0.0f,0.0f,0.0f, 0.0f,0.0f,0.0f,0.0f};

uniforms_s_shadow[1] = glGetUniformLocation(shaders0, "u_normal_mvp");
atributes_s_shadow[1].type = smq::GlUniform_Mat3;
atributes_s_shadow[1].m3 = {0.0f,0.0f,0.0f, 0.0f,0.0f,0.0f, 0.0f,0.0f,0.0f};

uniforms_s_shadow[2] = glGetUniformLocation(shaders0, "u_model");
atributes_s_shadow[2].type = smq::GlUniform_Mat4;
atributes_s_shadow[2].m4 = {0.0f,0.0f,0.0f,0.0f, 0.0f,0.0f,0.0f,0.0f, 0.0f,0.0f,0.0f,0.0f, 0.0f,0.0f,0.0f,0.0f};

uniforms_s_shadow[3] = glGetUniformLocation(shaders0, "u_tex");
atributes_s_shadow[3].type = smq::GlUniform_Int;
atributes_s_shadow[3].i = 0;

uniforms_s_shadow[4] = glGetUniformLocation(shaders0, "u_lightCount");
atributes_s_shadow[4].type = smq::GlUniform_Int;
atributes_s_shadow[4].i = 0;

mat[0] = new smq::Material(shaders0, uniforms_s_shadow, atributes_s_shadow);

std::vector<unsigned int> uniforms_s_post;
uniforms_s_post.resize(2);
std::vector<smq::GlAtribute> atributes_s_post;
atributes_s_post.resize(2);
uniforms_s_post[0] = glGetUniformLocation(shaders1, "u_tex");
atributes_s_post[0].type = smq::GlUniform_Int;
atributes_s_post[0].i = 0;

uniforms_s_post[1] = glGetUniformLocation(shaders1, "u_depth");
atributes_s_post[1].type = smq::GlUniform_Int;
atributes_s_post[1].i = 0;

mat[1] = new smq::Material(shaders1, uniforms_s_post, atributes_s_post);

}

void Qglsl() {
	for (int i = 0; i < 2; i++) {
		delete mat[i];
	}
}

