#pragma once
#include <Smq.h>

// This code is generated by SAM.

void initSam();
void quitSam();

enum Meshes : unsigned int {
};

smq::Mesh* GetMesh(Meshes mesh);

enum Textures : unsigned int {
	t_blocks,
};

smq::Texture* GetTexture(Textures texture);

enum Materials : unsigned int {
	s_shadow,
	s_post,
};

enum MaterialUniforms : unsigned int {
	s_shadow_vs_u_mvp = 0,
	s_shadow_vs_u_normal_mvp = 1,
	s_shadow_vs_u_model = 2,
	s_shadow_fs_u_tex = 3,
	s_shadow_fs_u_lightCount = 4,
	s_post_fs_u_tex = 0,
	s_post_fs_u_depth = 1,
};

smq::Material* GetMaterial(Materials material);
